package org.crowdfund.Config;

import lombok.NonNull;
import org.crowdfund.dao.DBAccessor;
import org.crowdfund.models.db.Donation;
import org.crowdfund.models.db.Project;
import org.crowdfund.models.db.User;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbTable;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.VersionedRecordExtension;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

/**
 * The type Dynamo db config.
 */
@Configuration
public class DynamoDBConfig {

    /**
     * Get dynamo db client dynamo db client.
     *
     * @return the dynamo db client
     */
    @Bean
    public DynamoDbClient getDynamoDbClient(){
       return DynamoDbClient.builder()
                .region(Region.US_WEST_2)
                .credentialsProvider(DefaultCredentialsProvider.create())
                .build();
    }

    /**
     * Get dynamo db enhanced client dynamo db enhanced client.
     *
     * @param dynamoDbClient the dynamo db client
     * @return the dynamo db enhanced client
     */
    @Bean
    public DynamoDbEnhancedClient getDynamoDbEnhancedClient(@NonNull final DynamoDbClient dynamoDbClient){
        return DynamoDbEnhancedClient.builder()
                .dynamoDbClient(dynamoDbClient)
                .extensions(AutoGeneratedTimestampRecordExtension.create(), VersionedRecordExtension.builder().build())
                .build();
    }

    /**
     * Get user table dynamo db table.
     *
     * @param dbEnhancedClient the db enhanced client
     * @return the dynamo db table
     */
    @Primary
    @Bean
    public DynamoDbTable<User> getUserTable(@NonNull final DynamoDbEnhancedClient dbEnhancedClient){
        return  dbEnhancedClient.table(User.TABLE_NAME, TableSchema.fromImmutableClass(User.class));
    }

    /**
     * Get project table dynamo db table.
     *
     * @param dbEnhancedClient the db enhanced client
     * @return the dynamo db table
     */
    @Primary
    @Bean
    public DynamoDbTable<Project> getProjectTable(@NonNull final DynamoDbEnhancedClient dbEnhancedClient){
        return  dbEnhancedClient.table(Project.TABLE_NAME, TableSchema.fromImmutableClass(Project.class));
    }

    /**
     * Get donation table dynamo db table.
     *
     * @param dbEnhancedClient the db enhanced client
     * @return the dynamo db table
     */
    @Primary
    @Bean
    public DynamoDbTable<Donation> getDonationTable(@NonNull final DynamoDbEnhancedClient dbEnhancedClient){
        return  dbEnhancedClient.table(Donation.TABLE_NAME, TableSchema.fromImmutableClass(Donation.class));
    }

    /**
     * Gets user db dynamo db accessor.
     *
     * @param dbEnhancedClient the db enhanced client
     * @param dynamoDbTable    the dynamo db table
     * @return the user db dynamo db accessor
     */
    @Bean
    public DBAccessor<User> getUserDBDynamoDBAccessor(@NonNull final DynamoDbEnhancedClient dbEnhancedClient,
                                                      @NonNull final DynamoDbTable<User> dynamoDbTable) {
        return new DBAccessor<User>(dbEnhancedClient, dynamoDbTable);
    }

    /**
     * Gets donation db dynamo db accessor.
     *
     * @param dbEnhancedClient the db enhanced client
     * @param dynamoDbTable    the dynamo db table
     * @return the donation db dynamo db accessor
     */
    @Bean
    public DBAccessor<Donation> getDonationDBDynamoDBAccessor(@NonNull final DynamoDbEnhancedClient dbEnhancedClient,
                                                              @NonNull final DynamoDbTable<Donation> dynamoDbTable) {
        return new DBAccessor<Donation>(dbEnhancedClient, dynamoDbTable);
    }

    /**
     * Gets project db dynamo db accessor.
     *
     * @param dbEnhancedClient the db enhanced client
     * @param dynamoDbTable    the dynamo db table
     * @return the project db dynamo db accessor
     */
    @Bean
    public DBAccessor<Project> getProjectDBDynamoDBAccessor(@NonNull final DynamoDbEnhancedClient dbEnhancedClient,
                                                            @NonNull final DynamoDbTable<Project> dynamoDbTable) {
        return new DBAccessor<Project>(dbEnhancedClient, dynamoDbTable);
    }
}
