package org.crowdfund.models.db;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbImmutable;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;

import java.math.BigDecimal;
import java.time.Instant;

@ToString
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDbImmutable(builder = Donation.DonationBuilder.class)
public class Donation {

    public static final String TABLE_NAME = "Donations";
    public static final String DONOR_ID = "donorId";
    public static final String PROJECT_ID = "projectId";
    public static final String PROJECT_ID_TO_DONATION_DATE_INDEX =
            "projectId-to-donationDate-index";
    public static final String DONOR_ID_TO_DONATION_DATE_INDEX =
            "donarId-to-donationDate-index";

    @Getter(onMethod = @__({@DynamoDbPartitionKey}))
    private String donationId;
    @Getter(onMethod = @__({
            @DynamoDbSecondaryPartitionKey(indexNames = {DONOR_ID_TO_DONATION_DATE_INDEX})}))
    private String donorId;

    @Getter(onMethod = @__({
            @DynamoDbSecondaryPartitionKey(indexNames = {PROJECT_ID_TO_DONATION_DATE_INDEX})}))
    private String projectId;
    private BigDecimal donationAmount;
    private String comment;
    @Getter(onMethod = @__({@DynamoDbAutoGeneratedTimestampAttribute,
            @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS),
            @DynamoDbSecondarySortKey(indexNames =
                    {PROJECT_ID_TO_DONATION_DATE_INDEX,
                            DONOR_ID_TO_DONATION_DATE_INDEX})}))
    private Instant donationDate;

    @Getter(onMethod = @__({@DynamoDbAutoGeneratedTimestampAttribute,
            @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_ALWAYS)}))
    private Instant updateDate;
    @Getter(onMethod = @__({@DynamoDbVersionAttribute}))
    private Integer version;
}
